import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../src/worker.js';
const password='test-only-operations-password-with-more-than-forty-chars';
function fixture(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const file of ['schema.sql','migrations/0002_local_usage.sql','migrations/0004_operations.sql'])db.exec(readFileSync(new URL('../'+file,import.meta.url),'utf8'));
 const env={SYNC_TOKEN:'public-app-key',OPS_ADMIN_SECRET:password,DB:{prepare(sql){let args=[];const stmt=db.prepare(sql);return{bind(...a){args=a;return this;},async all(){return {results:stmt.all(...args)};},async run(){return /^\s*SELECT/i.test(sql)?{results:stmt.all(...args)}:{meta:{changes:Number(stmt.run(...args).changes)}};}};},async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}}};return {db,env};}
async function call(env,path,{payload,cookie,auth,method,origin='https://test.invalid'}={}){return worker.fetch(new Request('https://test.invalid'+path,{method:method||(payload?'POST':'GET'),headers:{'content-type':'application/json',origin,...(cookie?{cookie}:{}),...(auth?{authorization:'Bearer '+auth}:{})},body:payload?JSON.stringify(payload):undefined}),env);}
async function login(env){const r=await call(env,'/v1/admin/login',{payload:{password}});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/);return r.headers.get('set-cookie').split(';')[0];}
const pulse=(token='a'.repeat(64),event='active')=>({installationToken:token,event,appVersion:'1.16.0',appBuild:'33',osVersion:'26.0'});
async function send(env,payload){return call(env,'/v1/telemetry/pulse',{auth:'public-app-key',payload});}

test('admin data is independent from public app key, login is same-origin and cookie signed',async()=>{const {env,db}=fixture();assert.equal((await call(env,'/v1/admin/overview',{auth:'public-app-key'})).status,401);assert.equal((await call(env,'/v1/admin/login',{payload:{password},origin:'https://evil.invalid'})).status,403);const cookie=await login(env);assert.equal((await call(env,'/v1/admin/overview',{cookie})).status,200);assert.equal((await call(env,'/v1/admin/overview',{cookie:cookie.slice(0,-1)+'x'})).status,401);const logout=await call(env,'/v1/admin/logout',{method:'POST'});assert.match(logout.headers.get('set-cookie'),/Max-Age=0/);db.close();});
test('wrong passwords are throttled and missing administrator configuration fails closed',async()=>{const {env,db}=fixture();for(let i=0;i<10;i++)assert.equal((await call(env,'/v1/admin/login',{payload:{password:'wrong'}})).status,401);assert.equal((await call(env,'/v1/admin/login',{payload:{password}})).status,429);delete env.OPS_ADMIN_SECRET;assert.equal((await call(env,'/v1/admin/login',{payload:{password}})).status,503);db.close();});
test('background heartbeat is not DAU; active retries deduplicate and first seen stays stable',async()=>{const {env,db}=fixture();assert.equal((await send(env,pulse(undefined,'heartbeat'))).status,200);const cookie=await login(env);let data=await (await call(env,'/v1/admin/overview',{cookie})).json();assert.equal(data.metrics.total,1);assert.equal(data.metrics.dau,0);assert.equal(data.metrics.reporting_recently,1);const original=db.prepare('SELECT first_seen_at FROM telemetry_installs').get();for(let i=0;i<3;i++)assert.equal((await send(env,pulse())).status,200);data=await (await call(env,'/v1/admin/overview',{cookie})).json();assert.equal(data.metrics.dau,1);assert.equal(data.metrics.wau,1);assert.equal(data.metrics.mau,1);assert.equal(data.trend.length,30);assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_days').get().n,1);assert.deepEqual(db.prepare('SELECT first_seen_at FROM telemetry_installs').get(),original);db.close();});
test('range boundaries, zero-filled dates and distinct devices across days are correct',async()=>{const {env,db}=fixture();const day=n=>new Date(Date.now()-n*86400000).toISOString().slice(0,10);for(const [id,age]of [['a',0],['b',6],['c',29],['d',30]]){db.prepare('INSERT INTO telemetry_installs VALUES(?,?,?,?,?,?)').run(id,day(age)+'T00:00:00Z',day(age)+'T00:00:00Z','1.0.0','1','14.0');db.prepare('INSERT INTO telemetry_days VALUES(?,?,1)').run(day(age),id);}db.prepare('INSERT INTO telemetry_days VALUES(?,?,1)').run(day(1),'a');const cookie=await login(env);const data=await(await call(env,'/v1/admin/overview?days=7',{cookie})).json();assert.equal(data.metrics.dau,1);assert.equal(data.metrics.wau,2);assert.equal(data.metrics.mau,3);assert.equal(data.trend.length,7);assert.equal(data.trend.at(-1).day,day(0));assert.equal(data.trend[0].day,day(6));assert.equal((await call(env,'/v1/admin/overview?days=999',{cookie})).status,400);db.close();});
test('extra identity or content fields are rejected and raw token is not stored',async()=>{const {env,db}=fixture();assert.equal((await send(env,{...pulse(),email:'private@example.com'})).status,400);assert.equal((await send(env,pulse('not-random'))).status,400);assert.equal((await send(env,{...pulse(),appVersion:'<script>'})).status,400);assert.equal((await call(env,'/v1/telemetry/pulse',{payload:pulse()})).status,401);assert.equal((await send(env,pulse())).status,200);const row=db.prepare('SELECT * FROM telemetry_installs').get();assert.notEqual(row.id,pulse().installationToken);assert.deepEqual(Object.keys(row).sort(),['id','first_seen_at','last_seen_at','app_version','app_build','os_version'].sort());db.close();});
test('forget erases metrics, leaves other installations and rejects delayed old-token retries',async()=>{const {env,db}=fixture();await send(env,pulse());await send(env,pulse('b'.repeat(64)));const r=await call(env,'/v1/telemetry/forget',{auth:'public-app-key',payload:{installationToken:pulse().installationToken}});assert.equal(r.status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_installs').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_days').get().n,1);assert.equal((await send(env,pulse())).status,410);assert.equal((await send(env,pulse('b'.repeat(64)))).status,200);db.close();});
test('metadata upgrades are reflected without duplicating installations; old daily rows expire',async()=>{const {env,db}=fixture();await send(env,pulse());const id=db.prepare('SELECT id FROM telemetry_installs').get().id;db.prepare('INSERT INTO telemetry_days VALUES(?,?,1)').run('2000-01-01',id);await send(env,{...pulse(),appVersion:'1.17.0',appBuild:'34'});const row=db.prepare('SELECT * FROM telemetry_installs').get();assert.equal(row.app_version,'1.17.0');assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_installs').get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_days').get().n,1);db.close();});
test('oversized login and telemetry bodies fail before database writes',async()=>{const {env,db}=fixture();assert.equal((await call(env,'/v1/admin/login',{payload:{password:'x'.repeat(3000)}})).status,413);assert.equal((await send(env,{...pulse(),extra:'x'.repeat(3000)})).status,413);assert.equal(db.prepare('SELECT COUNT(*) n FROM telemetry_installs').get().n,0);db.close();});

test('public admin shell cannot expose data, and is never cacheable',async()=>{
 const {env,db}=fixture();let assetPath;env.ASSETS={fetch:async request=>{assetPath=new URL(request.url).pathname;return new Response('<html>login</html>',{headers:{'content-type':'text/html'}});}};
 const r=await call(env,'/admin');assert.equal(r.status,200);assert.equal(assetPath,'/admin');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('x-robots-tag'),'noindex, nofollow');assert.match(r.headers.get('content-security-policy'),/connect-src 'self'/);
 assert.equal((await call(env,'/v1/admin/overview')).status,401);db.close();
});
